import {
  // Comida
  Pizza, Beef, Fish, Egg, Salad, Sandwich, Cookie, Cake,
  IceCreamCone, Drumstick, Soup, Croissant, Ham, Candy, CookingPot,
  // Frutas y verduras
  Apple, Carrot, Wheat,
  // Bebidas
  Coffee, Wine, Beer, CupSoda, Milk,
  // Cocina y restaurante
  UtensilsCrossed, ChefHat, Flame,
  // Tienda y comercio
  ShoppingBag, ShoppingCart, Package, Gift, Store, Tag, Percent,
  // Ropa y accesorios
  Shirt, Footprints, Scissors, Glasses,
  // Hogar
  Home,
  // Tecnologia
  Smartphone, Laptop,
  // Salud
  Heart, Pill,
  // Naturaleza
  Leaf, Flower2, Droplets,
  // Mascotas
  Dog, Cat,
  // Personas
  Baby,
  // Libreria y utiles
  Book, Pencil,
  // Herramientas
  Wrench, Hammer, Paintbrush,
  // General
  Sparkles, Star, Zap, PartyPopper, Clock, Camera, Gem,
  // Navegación y páginas
  Info, Phone, Mail, MapPin, MessageCircle, Truck, Calendar, CalendarDays,
  Images, Newspaper, HelpCircle, CreditCard, Wallet, Users, Briefcase,
  Building2, Trophy, Award, BookOpen, Music, Mic2, Play, Ticket,
  Dumbbell, Shield, Globe, Megaphone,
  // Verticales adicionales
  GraduationCap, Stethoscope, Car, Palette, Bed, Compass,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/** Mapeo agnóstico nombre → componente lucide. */
export const ICON_MAP: Record<string, LucideIcon> = {
  drumstick: Drumstick,
  beef: Beef,
  fish: Fish,
  pizza: Pizza,
  sandwich: Sandwich,
  soup: Soup,
  salad: Salad,
  egg: Egg,
  croissant: Croissant,
  cake: Cake,
  cookie: Cookie,
  "ice-cream-cone": IceCreamCone,
  candy: Candy,
  ham: Ham,
  "cooking-pot": CookingPot,
  apple: Apple,
  carrot: Carrot,
  wheat: Wheat,
  coffee: Coffee,
  "cup-soda": CupSoda,
  beer: Beer,
  wine: Wine,
  milk: Milk,
  "utensils-crossed": UtensilsCrossed,
  "chef-hat": ChefHat,
  flame: Flame,
  store: Store,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  package: Package,
  gift: Gift,
  tag: Tag,
  percent: Percent,
  shirt: Shirt,
  footprints: Footprints,
  glasses: Glasses,
  scissors: Scissors,
  home: Home,
  smartphone: Smartphone,
  laptop: Laptop,
  heart: Heart,
  pill: Pill,
  leaf: Leaf,
  "flower-2": Flower2,
  droplets: Droplets,
  dog: Dog,
  cat: Cat,
  baby: Baby,
  book: Book,
  pencil: Pencil,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  sparkles: Sparkles,
  star: Star,
  zap: Zap,
  "party-popper": PartyPopper,
  clock: Clock,
  camera: Camera,
  gem: Gem,
  info: Info,
  phone: Phone,
  mail: Mail,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  truck: Truck,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  images: Images,
  newspaper: Newspaper,
  "help-circle": HelpCircle,
  "credit-card": CreditCard,
  wallet: Wallet,
  users: Users,
  briefcase: Briefcase,
  "building-2": Building2,
  trophy: Trophy,
  award: Award,
  "book-open": BookOpen,
  music: Music,
  "mic-2": Mic2,
  play: Play,
  ticket: Ticket,
  dumbbell: Dumbbell,
  shield: Shield,
  globe: Globe,
  megaphone: Megaphone,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  car: Car,
  palette: Palette,
  bed: Bed,
  compass: Compass,
};
